USE world;

-- COMMAND TO SHOW THE TABLES.
SHOW TABLES;

-- COMMAND TO SELECT THE DATA TYPES FROM ALL THE COLUMNS OF THE DATABASE "WORLD" AND SORTS IT USING THE DATA TYPE BY ADCENDING ORDER.
SELECT DISTINCT DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'world'
ORDER BY DATA_TYPE ASC;

-- COMMAND TO SET TE UPDATES TO 0 SO THAT YOU CAN UPDATE FREELY
SET SQL_SAFE_UPDATES = 0;
ALTER TABLE city
ADD COLUMN  is_population_large BOOLEAN DEFAULT 0;

UPDATE city 
SET is_population_large = (population > 1000000)
WHERE population IS NOT NULL;



show warnings;

