USE world;

-- COMMAND TO SHOW THE TABLES.
SHOW TABLES;

-- COMMAND TO SELECT THE DATA TYPES FROM ALL THE COLUMNS OF THE DATABASE "WORLD" AND SORTS IT USING THE DATA TYPE BY ADCENDING ORDER.
SELECT DISTINCT DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'world'
ORDER BY DATA_TYPE ASC;

-- COMMAND TO ALTER THE TABLE CALLED CITY ADDING THE NEW COLUMN WHICH RETURNS A BOOLEAN VALUE (1->TRUE 0->FALSE) DEPENDING IF THE POPULATION
-- SURPASSES THE 1000000 
ALTER TABLE city 
ADD COLUMN is_population_large BOOLEAN 
GENERATED ALWAYS AS (population > 1000000) STORED;

-- COMMAND TO ADD A NEW COLUMN REGION_CODE TO THE COUNTRY TABLE WITH DEFAULT VALUE 'NA'
ALTER TABLE country ADD COLUMN region_code CHAR(3) DEFAULT 'NA';

-- COMMAND TO ENSURE THE POPULATION VALUE IS NEVER NEGATIVE IN THE CITY TABLE
ALTER TABLE city ADD CONSTRAINT chk_population CHECK (population >= 0);

-- COMMAND TO ENSURE COUNTRY CODE IS UNIQUE
ALTER TABLE country ADD CONSTRAINT unique_code UNIQUE (Code);

-- COMMAND TO CREATE AN INDEX ON CITY NAME FOR IMPROVED SEARCH PERFORMANCE
CREATE INDEX idx_city_name ON city(name);





